=== philatelist05/aic_2015/shared/src/main/resources/config.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://onion.ws14group2.aic.tuwien.ac.at"
           xmlns:onion="http://onion.ws14group2.aic.tuwien.ac.at">

	<xs:element name="config" type="onion:configType"/>

	<xs:complexType name="configType">
		<xs:all>
			<xs:element name="node" type="onion:nodeType"/>
			<xs:element name="target-service" type="onion:targetServiceType"/>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="nodeType">
		<xs:all>
			<xs:element name="common" type="onion:commonType"/>
			<xs:element name="local" type="onion:localType"/>
			<xs:element name="chain" type="onion:chainType"/>
			<xs:element name="directory" type="onion:directoryType"/>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="targetServiceType">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				Configuration for the
				RESTful service to provide
				random quotes.
			</xs:documentation>
		</xs:annotation>
		<xs:all>
			<xs:element name="host" type="xs:string">
				<xs:annotation>
					<xs:documentation xml:lang="en">
						The hostname where the
						server will be listening
						for incoming requests.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="port" type="xs:integer">
				<xs:annotation>
					<xs:documentation xml:lang="en">
						The port where the
						server will be listening
						for incoming requests.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="commonType">
		<xs:all>
			<xs:element name="local-mode" type="xs:boolean">
				<xs:annotation>
					<xs:documentation xml:lang="en">
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="host" type="xs:string">
				<xs:annotation>
					<xs:documentation xml:lang="en">
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="port" type="xs:integer">
				<xs:annotation>
					<xs:documentation xml:lang="en">
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="localType">
		<xs:all>
			<xs:element name="server-port" type="xs:integer">
				<xs:annotation>
					<xs:documentation xml:lang="en">
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="listening-host" type="xs:string">
				<xs:annotation>
					<xs:documentation xml:lang="en">
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="cellworkers-per-connectionworker" type="xs:integer">
				<xs:annotation>
					<xs:documentation xml:lang="en">
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="chainType">
		<xs:all>
			<xs:element name="heartbeat-interval" type="xs:integer">
				<xs:annotation>
					<xs:documentation xml:lang="en">
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="cellworkers-per-connectionworker" type="xs:integer">
				<xs:annotation>
					<xs:documentation xml:lang="en">
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="targetworker-timeout" type="xs:integer">
				<xs:annotation>
					<xs:documentation xml:lang="en">
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="directoryType">
		<xs:all>
			<xs:element name="heartbeat-timeout" type="xs:integer">
				<xs:annotation>
					<xs:documentation xml:lang="en">
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="thriftworker" type="onion:thriftworkerType"/>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="thriftworkerType">
		<xs:all>
			<xs:element name="min" type="xs:integer">
				<xs:annotation>
					<xs:documentation xml:lang="en">
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="max" type="xs:integer">
				<xs:annotation>
					<xs:documentation xml:lang="en">
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:all>
	</xs:complexType>
</xs:schema>

=== philatelist05/aic_2015/shared/src/main/resources/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<onion:config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:onion="http://onion.ws14group2.aic.tuwien.ac.at"
              xsi:schemaLocation="http://onion.ws14group2.aic.tuwien.ac.at config.xsd">
	<node>
		<common>
			<local-mode>true</local-mode>
			<host>54.93.220.183</host>
			<port>9090</port>
		</common>
		<local>
			<server-port>1080</server-port>
			<listening-host>localhost</listening-host>
			<cellworkers-per-connectionworker>5</cellworkers-per-connectionworker>
		</local>
		<chain>
			<heartbeat-interval>2000</heartbeat-interval>
			<cellworkers-per-connectionworker>20</cellworkers-per-connectionworker>
			<targetworker-timeout>2000</targetworker-timeout>
		</chain>
		<directory>
			<heartbeat-timeout>7000</heartbeat-timeout>
			<thriftworker>
				<min>3</min>
				<max>16</max>
			</thriftworker>
		</directory>
	</node>
	<target-service>
		<host>localhost</host>
		<port>8080</port>
	</target-service>
</onion:config>
